In [13]:
import json
import csv
import pandas as pd
import ast

In [109]:
temp_normalized = pd.read_json("normalized_fixations.jsonl", lines=True).iloc[0].to_dict()

261

In [113]:
print(len(temp_normalized["input_ids"]))
print(len(temp_normalized["inputs_embeds"]))
print(len(temp_normalized["fixations_normalized"]))
print(len(temp_normalized["fixations_attention"]))

261
261
237
237

In [19]:
df_hhrlf = pd.read_csv("preprocess_hhrlhf_split.csv")
df_hhrlf["chosen"] = df_hhrlf["chosen"].apply(ast.literal_eval)
df_hhrlf["rejected"] = df_hhrlf["rejected"].apply(ast.literal_eval)
df_hhrlf.head()

,Unnamed: 0.1,Unnamed: 0,chosen,rejected,chosen_score,rejected_score,question
0,0,0,"[{'role': 'user', 'content': 'What's a good ed...","[{'role': 'user', 'content': 'What's a good ed...",2.890750,1.614028,\n\nHuman: What's a good educational TV show f...
1,1,1,"[{'role': 'user', 'content': 'I'd like to comf...","[{'role': 'user', 'content': 'I'd like to comf...",1.017633,0.803172,\n\nHuman: I'd like to comfort a friend who re...
2,2,2,"[{'role': 'user', 'content': 'Does the quality...","[{'role': 'user', 'content': 'Does the quality...",2.090609,0.847201,\n\nHuman: Does the quality of your bed make t...
3,3,3,"[{'role': 'user', 'content': 'I want to visit ...","[{'role': 'user', 'content': 'I want to visit ...",0.547533,-0.320688,\n\nHuman: I want to visit an island with a go...
4,4,4,"[{'role': 'user', 'content': 'Can you tell me ...","[{'role': 'user', 'content': 'Can you tell me ...",-1.107227,-2.695792,\n\nHuman: Can you tell me why super bowl comm...

In [23]:
df_data_rewad = pd.read_json("after_preprocess_data_reward.jsonl", lines=True)
# df_data_rewad["input_ids_chosen"] = df_data_rewad["input_ids_chosen"].apply(ast.literal_eval)
# df_data_rewad["attention_mask_chosen"] = df_data_rewad["attention_mask_chosen"].apply(ast.literal_eval)
# df_data_rewad["input_ids_rejected"] = df_data_rewad["input_ids_rejected"].apply(ast.literal_eval)
# df_data_rewad["attention_mask_rejected"] = df_data_rewad["attention_mask_rejected"].apply(ast.literal_eval)
df_data_rewad.head()

,chosen_chat,input_ids_chosen,attention_mask_chosen,rejected_chat,input_ids_rejected,attention_mask_rejected
0,<s>[INST] What are places to visit in San Dieg...,"[1, 1, 3, 29473, 2592, 1228, 6331, 1066, 4019,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",<s>[INST] What are places to visit in San Dieg...,"[1, 1, 3, 29473, 2592, 1228, 6331, 1066, 4019,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,<s>[INST] How can I grow my own herbs for the ...,"[1, 1, 3, 29473, 2370, 1309, 1083, 3101, 1354,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",<s>[INST] How can I grow my own herbs for the ...,"[1, 1, 3, 29473, 2370, 1309, 1083, 3101, 1354,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,<s>[INST] How do I make sourdough starter? [/I...,"[1, 1, 3, 29473, 2370, 1279, 1083, 1806, 18961...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",<s>[INST] How do I make sourdough starter? [/I...,"[1, 1, 3, 29473, 2370, 1279, 1083, 1806, 18961...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,<s>[INST] I really love the in n out burger sp...,"[1, 1, 3, 29473, 1083, 2296, 2784, 1040, 1065,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",<s>[INST] I really love the in n out burger sp...,"[1, 1, 3, 29473, 1083, 2296, 2784, 1040, 1065,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,<s>[INST] What are some summer jobs my high sc...,"[1, 1, 3, 29473, 2592, 1228, 1509, 6329, 8562,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",<s>[INST] What are some summer jobs my high sc...,"[1, 1, 3, 29473, 2592, 1228, 1509, 6329, 8562,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [7]:
df_compute_fixation = pd.read_json("myRewardBase_compute_fixation.jsonl", lines=True)
df_compute_fixation.head()

,sentences,input_ids,fixations,attention_mask
0,[Are bobcats dangerous to humans? In the Uni...,"[[1, 1, 3, 29473, 5635, 28910, 29485, 2217, 10...","[[2.560306549072265, 9.210769653320312, 9.0547...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
1,[What are some fun easter activities for kids?...,"[[1, 1, 3, 29473, 2592, 1228, 1509, 1514, 2665...","[[4.088961124420166, 5.125532627105713, 6.1629...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
2,[How do I use resistance bands? There are a ...,"[[1, 1, 3, 29473, 2370, 1279, 1083, 1706, 1333...","[[3.162508010864258, 3.720036506652832, 1.7861...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
3,[I'd like to start getting into Shakespeare bu...,"[[1, 1, 3, 29473, 1083, 29510, 29483, 1505, 10...","[[3.075587272644043, 4.615506172180176, 1.0172...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
4,[What things should I look for in a new house ...,"[[1, 1, 3, 29473, 2592, 2490, 1791, 1083, 1681...","[[3.960257530212402, 7.51878023147583, 7.05977...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."

In [29]:
n = len(df_hhrlf)
for i in range(n):
    temp = df_hhrlf.iloc[i].to_dict()
    if 'educational' in temp['chosen'][0]['content']:
        print(i)
        print(temp['chosen'][0])

0
{'role': 'user', 'content': "What's a good educational TV show for my 4 year old to watch?"}

In [33]:
n = len(df_data_rewad)
for i in range(n):
    temp = df_data_rewad.iloc[i].to_dict()
    if 'educational' in temp['chosen_chat']:
        print(i)
        print(temp['rejected_chat'])

83
<s>[INST] What's a good educational TV show for my 4 year old to watch? [/INST] I think there are a lot of good ones out there, but a good starting point might be Sesame Street, which has been on the air for 45 years. </s><s>[INST] That's a good one, but he's seen a lot of it already. Any other ideas? [/INST] One of my favorites is Daniel Tiger's Neighborhood, which features Mr. Daniel Tiger, who's a very encouraging neighbor to all the kids who come to his house. They help him with his work, and he's there to support them through fun activities. </s><s>[INST] Do you know any others? They don't have to be new or recent [/INST] Well one I've enjoyed recently is Elena of Avalor. It's an animated Disney show about a teen princess, Elena. She's on a quest to find her missing parents, and has an enormous amount of wisdom for her age. </s>

In [117]:
n = len(df_compute_fixation)
for i in range(n):
    temp = df_compute_fixation.iloc[i].to_dict()
    if 'educational' in temp['sentences'][0]:
        print(i)
        # print(temp['sentences'][0])

32
40
139
147

In [119]:
rec_hhrlf = df_hhrlf.iloc[0].to_dict()
rec_data_reward = df_data_rewad.iloc[83].to_dict()
rec_compute_fixation = df_compute_fixation.iloc[147].to_dict()

In [97]:
# print(rec_data_reward['rejected_chat'])
# print()
# print(rec_data_reward['input_ids_rejected'])

In [123]:
print(rec_compute_fixation['sentences'][0])
print()
print(rec_compute_fixation['input_ids'][0])
print(len(rec_compute_fixation['input_ids'][0]))
print(len(rec_compute_fixation['fixations'][0]))

What's a good educational TV show for my 4 year old to watch?   I think there are a lot of good ones out there, but a good starting point might be Sesame Street, which has been on the air for 45 years.   That's a good one, but he's seen a lot of it already. Any other ideas?   One of my favorites is Daniel Tiger's Neighborhood, which features Mr. Daniel Tiger, who's a very encouraging neighbor to all the kids who come to his house. They help him with his work, and he's there to support them through fun activities.   Do you know any others? They don't have to be new or recent   Well one I've enjoyed recently is Elena of Avalor. It's an animated Disney show about a teen princess, Elena. She's on a quest to find her missing parents, and has an enormous amount of wisdom for her age.

[1, 1, 3, 29473, 2592, 29510, 29481, 1032, 1947, 14933, 5814, 2115, 1122, 1354, 29473, 29549, 1647, 2339, 1066, 3822, 29572, 29473, 4, 29473, 1083, 1841, 1504, 1228, 1032, 2823, 1070, 1947, 5181, 1343, 1504, 29493, 1330, 1032, 1947, 6383, 2073, 2427, 1115, 1086, 1042, 1201, 6151, 29493, 1458, 1427, 1518, 1124, 1040, 3191, 1122, 29473, 29549, 29550, 2035, 29491, 29473, 2, 1, 3, 29473, 2493, 29510, 29481, 1032, 1947, 1392, 29493, 1330, 1168, 29510, 29481, 3366, 1032, 2823, 1070, 1146, 2909, 29491, 5690, 1567, 6534, 29572, 29473, 4, 29473, 3155, 1070, 1354, 29419, 1117, 8871, 1088, 5654, 29510, 29481, 3915, 22626, 5847, 29493, 1458, 4958, 3732, 29491, 8871, 1088, 5654, 29493, 1461, 29510, 29481, 1032, 1983, 22653, 8190, 1066, 1312, 1040, 5319, 1461, 2335, 1066, 1284, 2902, 29491, 2074, 2084, 1481, 1163, 1284, 1539, 29493, 1072, 1168, 29510, 29481, 1504, 1066, 2528, 1474, 1827, 1514, 7058, 29491, 29473, 2, 1, 3, 29473, 3146, 1136, 1641, 1475, 3431, 29572, 2074, 1717, 29510, 29475, 1274, 1066, 1115, 1401, 1210, 6159, 29473, 4, 29473, 5441, 1392, 1083, 29510, 1101, 11074, 6683, 1117, 2512, 4362, 1070, 1098, 1820, 1039, 29491, 1429, 29510, 29481, 1164, 26461, 15433, 2115, 1452, 1032, 11567, 29081, 29493, 2512, 4362, 29491, 1753, 29510, 29481, 1124, 1032, 2593, 1066, 2068, 1327, 7693, 5154, 29493, 1072, 1427, 1164, 16090, 4326, 1070, 17447, 1122, 1327, 4363, 29491, 29473, 2, 2]
228
206

In [99]:
n = len(df_compute_fixation)
for i in range(n):
    temp = df_compute_fixation.iloc[i].to_dict()
    a1 = len(temp["input_ids"][0])
    a2 = len(temp["fixations"][0])
    print(a1, a2)

288 291
271 239
70 63
52 43
51 43
132 104
91 68
125 115
302 309
252 216
153 137
46 37
68 63
111 84
63 38
50 40
161 124
197 179
277 225
60 44
130 125
232 183
37 27
176 133
176 138
193 171
256 204
91 77
56 49
72 62
55 44
167 123
480 366
188 165
71 62
137 108
154 120
260 205
70 61
199 190
228 206
197 176
58 50
114 80
161 126
154 118
61 49
217 206
63 57
42 32
123 106
45 37
173 144
299 282
47 38
151 128
77 72
36 28
93 78
70 57
161 136
194 178
39 28
169 140
166 145
270 256
51 44
348 294
467 341
144 122
166 133
220 187
155 134
224 206
83 80
237 201
467 362
164 143
159 126
128 100
219 193
195 193
128 122
68 53
77 69
166 168
166 147
123 84
221 187
127 121
167 161
68 54
43 32
128 123
136 117
125 87
139 126
234 220
125 118
37 26
117 89
74 72
137 102
38 29
148 135
61 50
243 232
61 49
131 99
99 95
150 109
49 40
172 140
83 66
121 106
158 147
182 150
48 42
315 265
104 74
177 144
70 52
91 73
118 108
205 162
82 80
265 221
118 89
127 118
65 54
222 203
132 113
203 186
53 41
175 158
100 80
83 66
270 256
137 108
480 366
315 265
166 145
199 190
271 239
70 52
224 206
114 80
228 206
265 221
155 134
217 206
252 216
48 42
91 68
51 43
173 144
52 43
158 147
37 27
288 291
82 80
63 38
68 63
161 136
46 37
118 108
55 44
302 309
132 104
299 282
139 126
197 179
188 165
123 106
144 122
71 62
111 84
194 178
148 135
193 171
197 176
93 78
164 143
58 50
77 69
127 118
125 115
176 133
132 113
45 37
166 168
182 150
43 32
203 186
50 40
167 123
100 80
70 57
128 123
205 162
42 32
220 187
70 63
68 53
137 102
219 193
125 118
166 147
36 28
128 100
153 137
68 54
150 109
221 187
243 232
136 117
467 341
195 193
70 61
63 57
130 125
128 122
65 54
47 38
467 362
127 121
61 49
77 72
56 49
167 161
53 41
39 28
37 26
104 74
74 72
51 44
172 140
166 133
348 294
123 84
61 49
118 89
99 95
83 80
177 144
159 126
237 201
125 87
277 225
38 29
260 205
222 203
117 89
234 220
154 120
121 106
256 204
49 40
154 118
175 158
131 99
61 50
161 126
91 73
161 124
232 183
60 44
151 128
176 138
72 62
91 77
169 140
170 152
116 88
259 231
140 123
197 183
257 215
176 161
278 280
148 129
112 87
268 241
189 177
263 241
112 88
177 162
86 84
170 152
116 88
259 231
140 123
197 183
257 215
176 161
278 280
148 129
112 87
268 241
189 177
263 241
112 88
177 162
86 84
178 171
48 40
195 195
292 284
321 282
104 94
227 196
257 256
153 143
44 35
81 79
41 34
247 213
182 183
162 135
147 153
198 187
107 88
176 156
182 170
162 144
129 110
54 45
261 237

ImportError:
LlamaTokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.